name: ecs-build

on: push
                                              
jobs:
  build-deploy-dev:
    name: building & pushing to Dev
    runs-on: ubuntu-latest    

    environment:
      name: Dev
      url: https://dev.app

    env:
      VARIBALE1: ${{ secrets.VARIBALE1}}

    steps:
    - name: Test
      id: Test
      
      run: echo $VARIBALE1

  